### ISSUE TITLE
No module named 'quinnat'

### ISSUE THREAD

**Issue by Sfacim** [midsum-salrux/faux-legacy#3]
During installation process when running 'python3 faux/faux.py' this error comes up:

Traceback (most recent call last):
  File "faux/faux.py", line 3, in <module>
    import quinnat
ModuleNotFoundError: No module named 'quinnat'

I've installed quinnat. What do I do?

**Comment by midsum-salrux** [comment]
Have you run `pip3 install .` in the faux installation directory?

**Comment by Sfacim** [comment]
Yes, and that's worked, however now I'm getting a 

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

error after I've fixed all the other issues.

**Comment by midsum-salrux** [comment]
Have you set all the environment variables described in the README? What config file are you using (feel free to change/omit group/channel names)?

**Comment by Sfacim** [comment]
Yes! 
Here's the full error by the way:

File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sfacim/faux/faux/faux.py", line 133, in urbit_runner
    listener.urbit_client = urbit_client()
  File "/Users/sfacim/faux/faux/faux.py", line 20, in urbit_client
    client.connect()
  File "/Library/Python/3.8/site-packages/quinnat/quinnat.py", line 23, in connect
    self.ship = urlock.Urlock(self.url, self.code)
  File "/Library/Python/3.8/site-packages/urlock/urlock.py", line 13, in __init__
    self.channelUrl = self.url + "/~/channel/" + self.uid
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Process Process-1:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sfacim/faux/faux/faux.py", line 126, in discord_runner
    listener.urbit_client = urbit_client()
  File "/Users/sfacim/faux/faux/faux.py", line 20, in urbit_client
    client.connect()
  File "/Library/Python/3.8/site-packages/quinnat/quinnat.py", line 23, in connect
    self.ship = urlock.Urlock(self.url, self.code)
  File "/Library/Python/3.8/site-packages/urlock/urlock.py", line 13, in __init__
    self.channelUrl = self.url + "/~/channel/" + self.uid
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by midsum-salrux** [comment]
```
import quinnat

ship = "<your ship>"
url = "<your url>"
code = "<your +code>"
q = quinnat.Quinnat(url, ship, code)
q.connect()
```

Could you try running this in a python console and seeing whether the same error happens?

**Comment by Sfacim** [comment]
No errors came up. Ran smoothly.

**Comment by midsum-salrux** [comment]
That looks like the environment variables aren't set then. How are you setting them? A way that should work is `URBIT_URL="..." URBIT_SHIP="..." URBIT_CODE="..." DISCORD_TOKEN="..." python3 faux/faux.py`

**Comment by Sfacim** [comment]
Should the osgetenv be there? I just redid everything on the faux.py file and still the same error code.
