### ISSUE TITLE
Unicode emoji from discord break urbit -> discord

### ISSUE THREAD

**Issue by morzenmebs** [midsum-salrux/faux-legacy#4]
When a unicode emoji, such as `:smile:` is sent in the Discord channel, it renders as ������ in the Urbit channel and the python terminal gives the following message: 

```
 Process Process-4:
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "faux.py", line 135, in urbit_runner
    listener.run()
  File "faux.py", line 121, in run
    self.urbit_client.listen(urbit_listener)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "faux.py", line 135, in urbit_runner
    listener.run()
  File "faux.py", line 121, in run
    self.urbit_client.listen(urbit_listener)
  File "/home/urbot/.local/lib/python3.8/site-packages/quinnat/quinnat.py", line 31, in listen
    for event in pipe.events():
  File "/home/urbot/.local/lib/python3.8/site-packages/sseclient/__init__.py", line 63, in events
    line = line.decode(self._char_enc)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 322: invalid continuation byte
  File "/home/urbot/.local/lib/python3.8/site-packages/quinnat/quinnat.py", line 31, in listen
    for event in pipe.events():
  File "/home/urbot/.local/lib/python3.8/site-packages/sseclient/__init__.py", line 63, in events
    line = line.decode(self._char_enc)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 322: invalid continuation byte
```

After this occurs, the Discord to Urbit bridge remains working, while the Urbit to Discord bridge stops working, and only works again after restarting Faux. 
I am running Ubuntu 20.04 LTS on a cloud instance.

**Comment by midsum-salrux** [comment]
I was able to reproduce this. Working on a fix now.
